baseURL = 'https://hqmclay.github.io/repo/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = "PaperMod"

[params]
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
mainSections = ["posts"]
