baseURL = "https://hqmclay.github.io/hqmclay.github.io/"
languageCode = "en-us"
title = "My Site"
theme = "PaperMod"

[params]
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
mainSections = ["posts"]
